In [7]:
import math
import numpy as np

In [ ]:
a = 2 + 3
b = 2 - 3
c = 2 * 3
d = 2 / 3
e = 10 + 8 / 2
f = (10 + 8) / 2
g = pow(2, 3)

In [ ]:
x = 1
# Square Root
math.sqrt(x)
np.sqrt(x)
# Sine
math.sin(x)
np.sin(x)
# Arc Sine
math.asin(x)
np.arcsin(x)
# Cosine
math.cos(x)
np.cos(x)
# Arc Cosine
math.acos(x)
np.arccos(x)
# Tangent
math.tan(x)
np.tan(x)
# Arc Tangent
math.atan(x)
np.arctan(x)
# Natural Number e^x
math.exp(x)
np.exp(x)
# Natural Logarithm
math.log(x)
np.log(x)
# Base 10 Logarithm
math.log10(x)
np.log10(x)
# Base 2 Logarithm
math.log2(x)
np.log2(x)
# Maximum Value
max(x)
np.max(x)
# Minimum Value
min(x)
np.min(x)
# Absolute Value
abs(x)
np.abs(x)
# Signum Function
np.sign(x)
# Round to Nearest Integer
round(x)
np.round(x)
# Round towards 0
np.fix(x)
# Round towards +inf
math.ceil(x)
np.ceil(x)
# Round towards -inf
math.floor(x)
np.floor(x)
# Complex Conjugate
np.conj(x)

In [11]:
# np.linspace(firstElement, lastElement, numberOfElements)
new_array = np.linspace(0, 10, num=8)
print(new_array)

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [16]:
new_array = np.logspace(1, 4, num=10)
print(new_array)

[   10.            21.5443469     46.41588834   100.
   215.443469     464.15888336  1000.          2154.43469003
  4641.58883361 10000.        ]


In [ ]:
ones_array = np.ones(3,1)
zeros_array = np.zeros(2,3)
eye_array = np.eye(4)

In [22]:
# Array Transposition
x = [1, 2, 3, 4, 5]
x_transposed = np.transpose(x)
print(x)
print(x_transposed)

w = [1, 2, 3], [4, 5, 6], [7, 8, 9]
print(w)
w_transposed = np.transpose(w)
print(w_transposed)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
([1, 2, 3], [4, 5, 6], [7, 8, 9])
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [31]:
# Array Dimensions
y = np.ones([3, 2])
[row, col] = y.shape
print(row)
print(col)

3
2
